# Gauss Elimination
1. The Elimination Stage
2. Back Substitution

## 1. The Elimination Stage

In [2]:
import numpy as np


In [3]:
# Coefficients of Linear Equation

a = np.array([
[2, 7, -1, 3, 1],
[2, 3, 4, 1, 7],
[6, 2, -3, 2, -1],
[2, 1, 2, -1, 2],
[3, 4, 1, -2, 1]
], float)

# Constraint Vector of Linear Equation

b = np.array([[5],[7],[2],[3],[4]], float)
n = len(b)
x = np.zeros(n, float)

# Elimination

# k --> Fixed Rows

for k in range(n-1):
    for i in range (k+1, n):
        factor = a[k,k] / a[i,k]
        b[i] = b[k] - (factor * b[i])
        for j in range (k, n):
            a[i,j] = a[k,j] - (factor * a[i,j])


print(a)
print(b)

[[ 2.          7.         -1.          3.          1.        ]
 [ 0.          4.         -5.          2.         -6.        ]
 [ 0.          0.         -5.          0.52631579 -6.84210526]
 [ 0.          0.          0.          1.6374269   2.04678363]
 [ 0.          0.          0.          0.          0.95890411]]
[[ 5.        ]
 [-2.        ]
 [-4.73684211]
 [ 0.81871345]
 [ 0.2130898 ]]
